import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';
import { Observable } from 'rxjs/Rx';
import { Validators, FormBuilder } from '@angular/forms';
import { ToasterService } from "../../toaster/toaster.service";
import { PasswordService } from "../../services/password.service";


@Component({
    selector: 'app-password',
    templateUrl: './password.component.html',
    styleUrls: ['./password.component.css']
})
export class PasswordComponent {
    complexForm: FormGroup;
    model: any = {};
    constructor(private toasterService: ToasterService,
        private passwordservice: PasswordService,
        fb: FormBuilder
    ) {
        this.complexForm = fb.group({
            'CurrentPassword': [null, Validators.required],

            'NewPassword': [null, Validators.required],

            'AutogeneratedPassword': [null, Validators.required]
        }) 
    }

    // Update Current Password to New Password //

    //  submitForm(model:any){
    //       this.passwordservice.(model).subscribe(
    //          data=>{
    //               this.toasterService.showToaster('Password Successfully Changed!')
    //          error=>{
    //               this.toasterService.showToaster('Invalid Entries. Please Try Again!')
    //           }
    //        );
    //   }








    //     var password = generator.generate({
    //     length: 10,
    //     numbers: true
    // });

    // // 'uEyMTw32v9' 
    // console.log(password);


}
