import { Injectable } from '@angular/core';
import { Http, Headers, RequestOptions, Response } from '@angular/http';



@Injectable()
export class PasswordService {
    constructor(private http: Http) { }

    //   update(pwd:Password){
    //       return this.http.post('adad')
    //   }



    private jwt() {
        // create authorization header with jwt token
        let currentUser = JSON.parse(localStorage.getItem('currentUser'));
        if (currentUser && currentUser.token) {
            let headers = new Headers({ 'Authorization': 'Bearer ' + currentUser.token });
            return new RequestOptions({ headers: headers });
        }
    }
}

class Password {
    NewPassword: string;
    CurrentPassword: string;
    AutogeneratedPassword: string;
}